export const site = {
  name: 'Rik Kumar',
  role: 'Computer Science student at the University of Waterloo',
  title: 'Rik Kumar — Voxel Portfolio',
  description:
    'Portfolio of Rik Kumar, a University of Waterloo computer science student. Applied AI intern at the City of Edmonton and research extern at IBM Research Labs.',
  email: 'r88kumar@uwaterloo.ca',
  phone: '+1 (437) 772-1973',
  phoneHref: 'tel:+14377721973',
  resumeHref: '/resume.pdf',
  education: {
    school: 'University of Waterloo',
    program: 'Bachelor of Computer Science, Honours, Co-op',
    when: '2024 – Expected 2029',
    gpa: '3.8',
  },
  links: {
    github: 'https://github.com/rik305',
    linkedin: 'https://www.linkedin.com/in/rik-kumar-874297278/',
    leetcode: 'https://leetcode.com/u/rkumar7/',
    letterboxd: 'https://letterboxd.com/your-handle',
    goodreads: 'https://www.goodreads.com/user/show/your-id',
    chess: 'https://www.chess.com',
    lichess: 'https://lichess.org',
  },
  experience: [
    {
      org: 'City of Edmonton',
      role: 'Applied AI Intern',
      when: 'Jan. 2026 – Aug. 2026',
      where: 'Edmonton, AB',
      points: [
        'Refactored a dual-container architecture into a Python/Flask thin-client system, reducing dashboard load times by over 65% through optimized server-side spatial joins and a streamlined React/Leaflet interface for real-time neighborhood analytics.',
        'Engineered a GluonTS DeepAR forecasting model using a Negative Binomial output layer to handle sparse, low-volume incident data, achieving MAE of 0.02 and RMSE of 0.1231 through adaptive scaling.',
        'Developed an XGBoost-based predictive pipeline for crime forecasting, implementing cyclic temporal encoding and multi-scale lag features, to achieve an AUC-ROC of 0.88 on sparse incident data.',
        'Architected an asynchronous batch-processing NLP pipeline using Python and the Gemini API to classify high-volume incident logs into granular call types via a standardized domain taxonomy, resolving ambiguity downstream of Snorkel labeling.',
      ],
    },
    {
      org: 'IBM Research Labs',
      role: 'Undergraduate Research Extern',
      when: 'Oct. 2025 – Nov. 2025',
      where: 'Remote',
      points: [
        'Built a Qiskit pipeline to validate multi-qubit density matrices via automated trace-squared purity testing and eigenvalue analysis.',
        'Implemented automated error-handling routines to securely map validated pure states into state vectors for native quantum circuit initialization.',
      ],
    },
    {
      org: 'Estee Advisors',
      role: 'Tech Intern',
      when: 'May 2025 – Aug. 2025',
      where: 'Hybrid',
      points: [
        'Automated UI testing processes using JavaScript, Node.js, and Selenium WebDriver.',
        'Developed and optimized automated test scripts utilizing Excel.js for structured data processing, validation, and dynamic XPath management.',
      ],
    },
  ],
  projects: [
    {
      name: 'LeetPush',
      when: 'Aug. 2025',
      stack: 'Flask API, GraphQL API, Python, JavaScript, HTML',
      href: 'https://github.com/rik305/LeetPush',
      points: [
        'Developed a Chrome extension using JavaScript, HTML, and GraphQL to detect accepted LeetCode submissions and parse problem metadata.',
        'Built a Python/Flask backend to automate solution storage, code formatting, Git commits, and serve a local dashboard for tracking progress.',
      ],
    },
    {
      name: 'Winning FPL',
      when: 'Mar. 2025 – May 2025',
      stack: 'Pandas, NumPy, Scikit-learn, Matplotlib',
      href: 'https://github.com/rik305/DataScience---football',
      points: [
        'Engineered a player-rating algorithm using FPL API data to optimize team selection, boosting overall rank by 300% into the top 5th percentile.',
        'Built automated ETL pipelines using Pandas and NumPy to process historical player telemetry, fixture difficulty ratings, and rolling underlying metrics.',
      ],
    },
    {
      name: 'Commodity Price Forecasting',
      when: 'Dec. 2024 – Jan. 2025',
      stack: 'Pandas, NumPy, Scikit-learn, Matplotlib',
      href: 'https://github.com/rik305/Quantitative-Research---JPMorgan-Chase-Co./blob/main/Task1-JPM-QR.ipynb',
      points: [
        'Built a SARIMA time-series pipeline to forecast commodity prices and model dynamic storage contract valuations using NumPy and Matplotlib.',
      ],
    },
    {
      name: 'Credit Risk Analysis',
      when: 'Dec. 2024 – Jan. 2025',
      stack: 'Pandas, NumPy, Scikit-learn',
      href: 'https://github.com/rik305/Quantitative-Research---JPMorgan-Chase-Co./blob/main/Risk_assessment.ipynb',
      points: [
        'Developed Decision Tree and Logistic Regression classifiers on FICO score data to predict loan default probabilities and automate risk-tier bucketing.',
      ],
    },
  ],
  skills: [
    'Python',
    'C/C++',
    'JavaScript',
    'SQL',
    'Racket',
    'XGBoost',
    'GluonTS',
    'Scikit-learn',
    'Qiskit',
    'Pandas',
    'NumPy',
    'Polars',
    'Flask',
    'React',
    'Node.js',
  ],
} as const
